ALTER SESSION SET CONTAINER = xepdb1;
CREATE USER gesob_user IDENTIFIED BY "UsuarioTTD24$";
GRANT CONNECT, RESOURCE TO gesob_user;
GRANT CREATE VIEW TO gesob_user;

ALTER USER gesob_user QUOTA UNLIMITED ON USERS;